### ISSUE TITLE
2 Failed DataQuery Aggregate Tests

### ISSUE THREAD

**Issue by BruceWin** [shieldui/shieldui-lite#3]
Two DataQuery aggregate tests expecting "01/01/2005 12:59:42" are failing with "01/01/2005 13:47:42".

They are on line 945 and 1044 in /common/tests/data.js.

My time zone is GMT+2 (South African Standard Time).

![capture](https://cloud.githubusercontent.com/assets/12122595/14330334/671e1a8c-fc40-11e5-82a8-e13d146071cf.PNG)

**Comment by dtkujawski** [comment]
Same issue with me...
![image](https://cloud.githubusercontent.com/assets/10787424/14836960/f276cbee-0bd9-11e6-9ee9-f950497be281.png)

**Comment by tadhunt** [comment]
I'm having the same problem on
* shieldui-lite commit 03db121106664ab116f3bc9d88867fe47ac8f174
* OSX 10.10.5
* node v6.2.0
* npm 3.8.9
* grunt-cli v1.2.0
* grunt v0.4.5
  
```
Running "qunit:common" (qunit) task
Testing common/tests/index.html ......................................................................F..F.......
>> data.js - DataQuery aggregate
>> Message: average
>> Actual: "Sat Jan 01 2005 10:59:42 GMT-0800 (PST)"
>> Expected: "Sat Jan 01 2005 12:59:42 GMT-0800 (PST)"
>> at file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:1311
>>   at file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:1907
>>   at file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/common/tests/data.js:945
>>   at file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:895
>>   at file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:1024
>>   at process (file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:583)
>>   at begin (file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:628)
>>   at file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:644

>> data.js - DataQuery group
>> Message: average
>> Actual: "Sat Jan 01 2005 10:59:42 GMT-0800 (PST)"
>> Expected: "Sat Jan 01 2005 12:59:42 GMT-0800 (PST)"
>> at file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:1311
>>   at file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:1907
>>   at file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/common/tests/data.js:1044
>>   at file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:895
>>   at file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:1024
>>   at process (file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:583)
>>   at begin (file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:628)
>>   at file:///Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/external/qunit/qunit.js:644

Warning: 2/508 assertions failed (239ms) Use --force to continue.

Aborted due to warnings.
[tadhunt@Scarface shieldui-lite ((03db121...))]$ 

```

If I comment out the offending lines (data.js;945 and 1044), compilation gets further, but still fails during uglification:

```
Running "uglify:core" (uglify) task
TypeError: Cannot create property 'warnings' on boolean 'true'
    at Object.exports.minify (/Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/node_modules/grunt-contrib-uglify/tasks/lib/uglify.js:65:35)
    at /Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/node_modules/grunt-contrib-uglify/tasks/uglify.js:106:25
    at Array.forEach (native)
    at Object.<anonymous> (/Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/node_modules/grunt-contrib-uglify/tasks/uglify.js:36:16)
    at Object.<anonymous> (/Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/node_modules/grunt/lib/util/task.js:300:12)
    at /Users/tadhunt/Documents/Personal/go/src/github.com/shieldui/shieldui-lite/node_modules/grunt/lib/util/task.js:227:11
>> Uglifying source "dist/js/core.js,dist/js/data.js,dist/js/util.js" failed.
Warning: Uglification failed.
Cannot create property 'warnings' on boolean 'true'. 
 Use --force to continue.

Aborted due to warnings.
```

**Comment by shieldui** [comment]
Merged https://github.com/shieldui/shieldui-lite/pull/6 which fixed that
